### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by Kirtai** [codefrau/Smalltalk78#4]
Is there a licence for the Smalltalk code?
Or at least the updates?

**Comment by codefrau** [comment]
I'm pretty sure at least the updates are MIT. I'll defer to @Daningalls for the authoritative answer ...

**Comment by Kirtai** [comment]
Hi, are there any updates on this? I would love to have an ST78/76 system to work on but I'd hate to have to abandon my efforts later due to a licencing issue.

**Comment by codefrau** [comment]
I talked to both Dan Ingalls and Alan Kay.

From Dan:

> It began as a late St-76 in the form of an St-78 port in which I (and I believe only I) rewrote the graphics kernel around a single call on BitBlt.  In that sense it can also be seen as an early St-80.  Which should allow it to ride along on the coattails of the release of St-80 historical images (as did Squeak).
> 
> Since that time I have added to it and altered it greatly or not so, depending on what version we’re talking about.
> 
> Plus, early in its evolution as St-78-reborn, Yoshiki added a “Dollar” hand character recognizer plus a bunch of features to create shapes, and Yoshiki and I added morphic-like scheduling of windows and other shapes.  Also you added the whole external file and update management system.  Plus, Alan added a project management and navigation system.

Alan replied:

> My take on this is similar to yours. I would get the "revivalists" to all sign a consent form and tack it onto the already existing St-80 license as "early version of ST-80" (which it actually is in most important ways).

The "revivalists" Alan mentioned are me, Dan, Ted Kaehler, Yoshiki Ohshima, and Alan himself. Ted was involved in relicensing Squeak as a direct derivative of Smalltalk 80. 

So the license is as with Squeak:
1. the original image and source code is licensed under Apache 2.0
2. all contributions since then, and in the future, are MIT-licensed
3. my JavaScript VM source code is MIT licensed

**Comment by Kirtai** [comment]
Thank you, that's pretty much exactly what I was hoping for :)
